### ISSUE TITLE
Inconsistent use of System Policy

### ISSUE THREAD

**Issue by abrunstrom** [taps-api/drafts#100]
In 4.2 of the architecture draft, System Policy is defined as the algorithm used to identify candidates and do racing based on the provided connection properties. 
In the implementation draft, system policy is an input to the algorithm.

The definition in the implementation draft is more natural to me, system policy is an input. One solution could be to use the term Policy System rather than System Policy in the architecture draft and update the description to something like:

Policy System : A Transport Service Policy System defines the algorithm used to combine and reconcile connection properties from the application with dynamic system policy and implementation defaults to determine how it will gather candidate paths and protocols ({{gathering}}) and race the candidates during establishment ({{racing}}).

Once the text for the architecture draft is set, minor tweaks can be applied to the implementation draft to conform.

**Comment by tfpauly** [comment]
I think System Policy should refer to the part of the Operating System or TAPS System that controls which paths are allowed for what operations. So yes, system policy is an input. I'd rather just re-work the architecture draft here to match the implementation.

**Comment by tfpauly** [comment]
Updated definition to be more inline with the usage in the implementation draft!
