### ISSUE TITLE
Cut appendix C

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#104]
The current appendix C "Transport Parameters" discusses:

- details of which transport and path selection properties can take which preference levels
- details of how querying of transport parameters and properties works

It's not currently up to date with -00. 

The former set of restrictions already appears in §5.2, which relaxes some of the restrictions but points out that applications should take care to select consistent preferences while implementations should fail early on inconsistent application preferences, which would seem to be an appropriate level of detail for -00.

The latter content appears in §9 in abbreviated form.

I think we can cut this for -00; objections? @mwelzl, @theri, @philsbln, opinions?

**Comment by mwelzl** [comment]
Yes... I like the idea of these tables at the end to summarize what is written earlier, but then (as has happened) these tables can get out of sync, so I think it's easier to include them later, not while things are changing. Right now I agree that the mismatch makes things quite confusing.
