### ISSUE TITLE
API 5.2 Connection Groups

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#108]
The API document says:
```
* Efficient use of Connection Groups:
  This boolean property specifies whether an
  application considers it useful to create Connection Groups, e.g. to
  explicitly prioritize between Connections within a Connection Group. This
  property will tend to select multistreaming transport protocols, which can
  multiplex Connections into a Connection Group over a single flow. This is not
  a strict requirement. The default is to not have this option.
```
I'm not sure I follow this. The text doesn't seem to match the option name: it isn't saying use connection groups efficiently or not, it's specifying whether connection groups can be used at all. It's also not clear why prioritisation is given as an example. 

Would it be clearer written something more like the following?
```
* Multiplex connections:
  This boolean property specifies that the application would prefer multiple
  Connections between the same endpoints to be treated as a Connection
  Group and multiplexed onto a single underlying transport connection where
  possible, for reasons of efficiency. This is not a strict requirement. The 
  default is to not have this option.
```

**Comment by britram** [comment]
yep. Although you *still* have to explicitly entangle connections by cloning them if you want them to be guaranteed to be within a connection group.

**Comment by csperkins** [comment]
...which makes me question why we need this parameter?

**Comment by britram** [comment]
To explicitly prefer multistreaming protocols during selection, because you wrote your app to clone connections instead of cloning preconnections.

**Comment by britram** [comment]
(see #118)
