### ISSUE TITLE
API 5.2 "Notification of special errors"

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#110]
What makes these errors "special"? It seems a strange term to use, and the meaning is unclear.

**Comment by mwelzl** [comment]
I didn't write this, but I think it was an effort to lump together, from minset, two quite different types of errors:  1) notification of excessive retransmissions; 2) notification of icmp error message arrival.  Any suggestions for a common term?

**Comment by csperkins** [comment]
If it's just those two types of errors, we can probably just list them...

**Comment by mwelzl** [comment]
...which is what I did in minset  :)

**Comment by britram** [comment]
so the suggestion is to split these out into two protocol selection properties?

**Comment by csperkins** [comment]
yes, I think so

**Comment by britram** [comment]
all right then, see #119
