### ISSUE TITLE
API 7: maximum message size

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#113]
Section 7 of the API says: "Messages may be arbitrarily large; however, there may be system and Protocol Stack dependent limits on the size of a data object which can be transmitted atomically". Some protocols have a limit on the maximum message size, not just the maximum size that can be can transmitted atomically. The draft should mention that.

**Comment by mwelzl** [comment]
That's the readable property "Maximum non-partial Message size on send" in section 9.1. Maybe the text here should refer to this section...

**Comment by csperkins** [comment]
I read "Maximum non-partial Message size on send" as the message could be larger than that, but would then have to be delivered in pieces. Some protocols have an absolute maximum message size.

**Comment by mwelzl** [comment]
I think the "partial" bit makes it a bit confusing (I'm not a fan of that either - in minset it was phrased as "The maximum transport message size that can be sent, in bytes"); however, we also have another readable property that's quite explicitly about fragmentation in §9.1:

"Maximum Message size before fragmentation or segmentation: This numeric property, if applicable, represents the maximum Message size that can be sent without incurring network-layer fragmentation and/or transport layer segmentation at the sender. This property is read-only."

so in context, I think it's clear enough?

**Comment by britram** [comment]
@csperkins is there an action for -00 here?

**Comment by mwelzl** [comment]
Let's just drop the "non-partial" bit. I think it only adds confusion. I did a search for "non-partial" in the text; there are 6 matches. I think all of these 6 instances could safely be removed and would only make things clearer.

**Comment by britram** [comment]
WFM (for -00; I think we should do a more rigorous review of the terminology and operation of partial/full Messages post-London). Can you make this change in your editorial pass PR?

**Comment by mwelzl** [comment]
I just did it, but not in the PR: I finished the PR, then saw this, then decided to update the master instead (this is not a very disruptive change for sure), and THEN remembered that PRs can simply be updated... oh well. Anyway, fixed!

**Comment by mwelzl** [comment]
Clearly, git is for less childish people than me... after seeing that I close an issue and someone re-opens it, I'm waaaaay to tempted to close it again just for the heck of it!  :-D

**Comment by britram** [comment]
wait, what just happened here?

**Comment by mwelzl** [comment]
So, seriously: I don't know why @csperkins re-opened: I think he thought you're talking to him, but I believe you talked to me?  I did the update and I do think the case is closed; I think the right thing to do is for @csperkins to leave the issue open if he's not happy with only removing "non-partial" and wants this to be even clearer.

**Comment by britram** [comment]
(I've also been leaving issues open until the PRs fixing them land, since issues should reflect the state of master. But yeah, I think we're just confused.)

**Comment by csperkins** [comment]
I reopened because I don't think this is addressed yet. PR incoming.
