### ISSUE TITLE
Cut appendix B

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#114]
Appendix B of the API draft provides a sample concrete definition of the API, written in Go. Having concrete examples of the API is clearly useful, but I question whether this draft is the right place for them, since we don't want to bless a particular API variant. Suggest this appendix be moved to either the implementation draft, or a separate example API implementation draft.

**Comment by britram** [comment]
The intention here is to show that the API is reasonably expressible and expressive in at least one modern language. I'd be more than happy to replace it with links to the code and documentation for now though. (Eventually, *examples* would be more useful than the sketch though.)

**Comment by csperkins** [comment]
@britram makes sense.
