### ISSUE TITLE
Re-add batching Send operations to API and Implementation

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#136]
In aligning the implementation with the API for the initial draft, we removed this text since we still need text in the API:

#### Batching Sends

Since sending a Message may involve a context switch between the application and the transport system, sending patterns that involve multiple small Messages can incur high overhead if each needs to be enqueued separately. To avoid this, the application should have a way to indicate a batch of Send actions, during which time the implementation will hold off on processing Messages until the batch is complete. This can also help context switches when enqueuing data in the interface driver if the operation can be batched.

**Comment by gorryfair** [comment]
This seems equivalent to the idea of PUSH in existing systems and would make sense for lots of short write calls.

**Comment by britram** [comment]
+1.

The higher-level question here is how to support high-performance applications. Send batching is one thing you can do here. Receive batching would be another obvious one. Zero-copy is another, though that's probably so tied to implementation and platform that it's not useful to standardize. But there should be some way for this interface to coexist with it...

**Comment by mwelzl** [comment]
+1 from me too

**Comment by philsbln** [comment]
+1 

In my opinion, support for high-performance applications is nothing we can add to the API, but rather something we must sure to not prevent or make hard to implement.
So we should ask ourselves for every point in the API "can this be implemented zero-copy" or "can an implementation batch this" – if the answer is no, we have to fix that.

**Comment by britram** [comment]
this one seems to have consensus and does not seem to be too much work. @tfpauly, if you can get a PR in in the next week or so let's ship it with ietf-00...

**Comment by tfpauly** [comment]
I'll try to get this in soon!

**Comment by britram** [comment]
fixed with merge of #171
