### ISSUE TITLE
overstatement?

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#139]
The text says:
   It
   would not be an overstatement to say that this simple API is the
   reason the Internet won the protocol wars of the 1980s.  
I think this is just an opinion: claiming this is the ONE reason, is an overstatement. When I was on the "other side" of this as an X.25 developer, the API was not the reason. The killer pain was the "congestion experienced" clearing message that caused spiralling complexity in how to realise the equivalent of source quench. I'm not convinced this is the ONE reason - I'm content it is A key reason.

**Comment by britram** [comment]
agreed, will fix
