### ISSUE TITLE
informing an app about ICMP

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#141]
TEXT:
      informed when an ICMP error message arrives.
- I think this is OK. but is this intended to be for soft-errors, since hard-errors break the connection? I think I get this, although some transports obvioulsy "eat" the ICMP packets they receive, and many ICMP messages have no meaning to an app, but some can be important. Tell me more please...

**Comment by mwelzl** [comment]
this comes from minset - and so it’s based on the rfc “soft error” text. true, no guarantee that you get it.

**Comment by gorryfair** [comment]
So, maybe the next rev of  text should just say this and it will be fine.
