### ISSUE TITLE
Clean up Capacity Profile

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#142]
TEXT:
      application's expectation of the dominating traffic pattern for...

- I am calling this out in case I think different to others... and then I want to discuss, but it could also be that this was an oversight on which we alreday agree... either way there's a lot of comment here on just a few words.

- I really do not like this. To me this is expressing QoS properties, and I think this is the wrong way to do this. I’d be OK if the application instructs the network to use a particular treatment. When an endpoint requests a treatment, the network can either treat it in a default way, or give it the treatment it requests. If the application sends data incompatible with the treatment, then the performance observed may suffer - but that is exactly correct because that is how the application asked its data to be treated. I'd for example prefer:
     application’s expectation of the treatment the network should provide for...

I am really against the application trying to label it’s data as being of some type (which I think this part currently does). To me, a QoS framework on the other hand, sets certain parameters in the network and then “labels” the flows in some way to use them. That’s a different approach, and one that demands more support from the network.
- Similarly, I did not like:
     The application is not interactive.  
- I’d prefer:
     The application does not wish traffic to be treated as interactive.  
  ... or something alike.

**Comment by philsbln** [comment]
The application labeling what they are going to do and that traffic pattern they expect is one of the key ideas of the original Socket Intents work. It allows optimizing locally for the expected pattern in a way that is impossible without. 
 - This kind of information is intended to be used for path, endpoint, and protocol selection logic.
 - This information may also be used to automatically derive defaults for protocol parameters.
 - This information is _not_ intended to be used for polarization or for QoS labeling.

I guess we must include this as a clear warning to make sure it is not mixed up with QoS.

For your example: "The application is not interactive." is easy for a developer.
What it really states: "The programmer opening this socket suggests that latency and bandwidth variations will most likely have no observable user impact" – therefore the OS might, when combined with other hints like Resilience and Traffic Category, establish the connection over an unstable, but high bandwidth path.

**Comment by britram** [comment]
One concrete proposal (around the table in London):

Replace "Capacity Profile" and "Instantaneous Capacity Profile" with a three-state variable for traffic classification which can be used for DSCP marking and local AQM:

1. Default
2. Scavenger
3. Low-latency

**Comment by mwelzl** [comment]
I like the choice, but let's not think about this in terms of DSCP marking. As I said at the meeting, DSCP marking can take more values that we may want to offer ( table 1 in https://tools.ietf.org/html/draft-ietf-tsvwg-rtcweb-qos-18 ) - but these choices map onto other decisions for a whole connection, e.g. turning Nagle on/off, etc. etc. .... sure they CAN affect DSCPs values too, depending on what the system does. I think a reasonable implementation choice would be to let them affect DSCP values in addition to other things, but let a possible per-message DSCP choice overrule this 1-out-of-3 choice here.

**Comment by gorryfair** [comment]
Yes - I'm OK with each of these three (and also more if we choose carefully) - but I do agree that an App *CAN* also set a DCSP value that overrides the default. That's important.

**Comment by philsbln** [comment]
I would prefer a mixture of @britram and @mwelzl suggestions.

   0. Default 
   1. Low-latency data / Interactive data
   2. Audio
   3. Interactive Video with or without Audio
   4. Non-Interactive Video with or without Audio
   5. Scavenger

Which is really close to the proposal @tfpauly made.

**Comment by gorryfair** [comment]
You've named these by application-type;-).
So what are the properties of the service being offered for 2,3,4?

Gorry

**Comment by gorryfair** [comment]
I will dig for some words to suggest for the treatments

Gorry

**Comment by gorryfair** [comment]
To try some words for the treatments (this maybe is not so easy):

1.  Low-latency / Interactive data   (for example could be EF PHB, AC_VO)
2. MM Streaming  (for example could be AF3n PHB, AC_VI)
3. Low Latency Data   (for example could be AF2n PHB. AC_VI)
4. High Throughput Data (for example could be AF2n PHB, AC_BE)
5. Default (for example could be BE PHB, AC_BE)
6. Scavenger (for example could be LE PHB, AC_BK)

Suggestions only for AC's (they probably should not appear in a RFC), but probably should just point to RFC 8325.

Gorry

**Comment by britram** [comment]
closed when #233 merged
