### ISSUE TITLE
Send Properties: Per-send or per-message?

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#146]
Should we specify in the API more clearly if properties around sending apply more to the Send() operation or the Message itself?

In my implementation, I'm treating things like "Idempotent" as per-send, since I could technically have a bit of a message at the beginning I want to do 0-RTT with, but the rest of the data may not be fully idempotent.

However, ordering and reliability (and likely niceness) is a property of the entire Message, and so if I'm sending a Message in multiple Send()s, we want the same properties across all calls.

**Comment by philsbln** [comment]
That introduces a third kind of properties – do we want this kind of complexity?

In my opinion, we should only have Send Properties. Whether they can be applied to partial messages is transport-protocol and implementation specific. So if your TCP stream is a single message (no framers/de-framers), one can indeed only mark the first part as idempotent.
The consequence is that we need to think about when this will raise an error.

**Comment by mwelzl** [comment]
I'd say it should be per-message, not per-send, and I also agree that we should keep things simple. In particular, from Tommy, 

> "Idempotent" as per-send, since I could technically have a bit of a message at the beginning I want to do 0-RTT with, but the rest of the data may not be fully idempotent.

sounds really messy to me!  Why not have two separate messages instead, an idempotent one and a non-idempotent one? What's the argument for dividing a message into two separate parts with different properties?

**Comment by philsbln** [comment]
As long as we treat TCP streams as a large message, we need to support Send Properties on partial messages, e.g., for 0-RTT

**Comment by mwelzl** [comment]
i thought this tcp-stream=message idea was finally behind us??  that was agreed between tommy and me in london, at least

**Comment by britram** [comment]
for bookkeeping purposes: ISTM that #200 addresses this one, too.

**Comment by philsbln** [comment]
As far as I am concerned, #200 and #201 seem to have fixed this issue.

**Comment by britram** [comment]
closed by #200 and #201
