### ISSUE TITLE
API: Add text for sending partial messages

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#148]
Send needs to take:
- Data 
- Which message (message object contains message properties)
- Flags: end-of-message, end-of-connection-send

**Comment by csperkins** [comment]
Is data separate to the message?

**Comment by britram** [comment]
@tfpauly: would you like to take a swing at this one?

**Comment by britram** [comment]
Timing out. ietf-01 it is.

**Comment by mwelzl** [comment]
What is the expected receive behavior - can an application also receive partial messages?

I'm asking because SCTP has this ability, and then needed to include means to inform the receiver that message delivery has been aborted (when not transmitting reliably and a message fragment is missing)

=> this is a path of complexity that I think we shouldn't take, just for the sake of allowing large messages to be transferred as such. The alternative is to force them to be small...

**Comment by mwelzl** [comment]
I thought so (about receiving). So how do you handle a missing partial message? Do you assume that the app can always be told?  I’m trying to remember, but there was a problem with this...

**Comment by mwelzl** [comment]
Another problem with this: receiver-side HOL blocking between streams. One stream gets a very long message, all the others get blocked. If you allow very large messages, SCTP needs to use NDATA to deal with this (which internally divides the messages). I think that's absolutely fair to expect, as this is really the right way to handle this. How does QUIC handle very large messages? Does it divide them, or will it get HOL blocking delay?

If all protocols that we'll use divide large messages into smaller chunks for prioritization and avoiding HOL delay between streams, than maybe this is a non-problem. Else - I'm just saying, a simple way around all of this is to put a small upper bound on the size of a message that we support. Or we document the risk...

**Comment by tfpauly** [comment]
@mwelzl I'm not sure what the concern is for a missing partial message. When you receive, you get two pieces of information: the newly received data, and the associated Message object. If you could only receive part of the message (it's not complete), you will be able to check that this isn't the entire Message, and you'll be able to call receive on the connection again to get more data, which may be for the same Message. If there's an error before being able to receive the entire message, you'll get an error in the receive call letting you know that message was incomplete.

You don't need HOL blocking if each receive callback tells you which message the data is associated with.

**Comment by mwelzl** [comment]
First, about HOL blocking:

I'll conclude: this is okay; it assumes that the transport below does the right thing, but I think that makes sense to assume.

Just to explain what I mean: with SCTP, and without NDATA (interleaving - a pretty new feature, RFC 8260), receive calls would *always* only give you data from the same message until you finally have it complete. That produces HOL blocking, and I believe it was done to simplify the app's life on the receiver side.

But I think SCTP-before-NDATA isn't good behavior, and I believe QUIC would do the right thing too, so I think what you propose is fine.

**Comment by mwelzl** [comment]
Second, about a missing partial message:

> If you could only receive part of the message (it's not complete), you will be able to check that this isn't the entire Message, and you'll be able to call receive on the connection again to get more data, which may be for the same Message.

So let's assume that you have an unreliable transport below, to which we hand partial messages, and some of them never make it. The receiver only gets parts 1 and 3, but part 2 will never arrive. Is this a case that we want to consider? We'd have to document that the receiver's deframer must be able to correctly detect such cases.

Or do you assume that the underlying transport would always ensure that all parts of a message arrive, or else tell the receiver-side transport system about it? Then we'll at least need a signal to the application to forward that information, to tell it that a message is incomplete.

**Comment by tfpauly** [comment]
Closed by #200
