### ISSUE TITLE
Handling conflicts among path/protocol selection properties

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#149]
See thread at https://mailarchive.ietf.org/arch/msg/taps/i8Ax-WqOoOg4obYU8MgBzb0F3oc

Suggested resolution: implementation must have a deterministic tiebreaker, current recommendation is that path properties take precedence. API should note expected behavior. There should be additional text on candidate selection and ordering.

**Comment by tfpauly** [comment]
Give example for path candidate gathering and sorting (get selection properties, get available paths in system preferred order, walk through them cancelling out the prohibited ones, and ranking preferences; get ultimate list). Do the same for protocols likely.

**Comment by theri** [comment]
Added text to API and Implementation drafts on branch "conflicting-policies".
API has an example, implementation still needs one. Feel free to add, otherwise I'll come back to it later today or tomorrow.

**Comment by philsbln** [comment]
I guess that works for -00

For -01, we might want to integrate the resolution a little bit more into the decision process.

**Comment by philsbln** [comment]
Resolved by PR #167
