### ISSUE TITLE
Add Delivered event?

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#151]
From a comment at IETF101:

The `Sent<>` event fires when a message has been sent (i.e., passed down to the underlying protocol stack, or passed through that stack to the kernel.) For stacks that can support it, `Delivered<>` should fire when the traffic has been positively acknowledged by the other side.

Whether acknowledgements can be signaled should also be a protocol selection property.

**Comment by mwelzl** [comment]
I note that this also relates to item 5 in #147, which is about delivering not only to the stack, but to the app.

Can someone explain to me what the point of this is? Both for the one here, and the one in #147?
What confuses me is: once a protocol would ACK something, it would have it inside its own send buffer, and that takes it out of the control of the application - so what's an application supposed to do with this information?  (and is it maybe only the information in #147 that is really useful?)

**Comment by philsbln** [comment]
I asked a similar question on London and got at least three people shouting "no - don't do that" at me… with different arguments.
In my opinion, delivery events are definitely not in a minimal functionality set, but useful if available.

If we want to be forward-compatible to such transports, we should define multiple events:
 - Sent (handed over to transport system)
 - Acknowledged (received by the remote transport system)
 - Delivered (handed over to the remote application)

I guess the real discussion is how much research/forward compatibility to add to the API.
My current feeling is that the authors try to minimize functionality, while external feedback is to add features that can be implemented using today's protocols (like the Acknowledged message and some transport automation features) or which might come soon as experimental protocols.
Maybe we really need three sets of functionality:
 1. Minimal (every TAPS system must implement)
 2. Standard (usable today, every TAPS system on a reasonably powerful platform should implement)
 3. Experimental (experimental stuff / forward compatibility that might be implemented and that we don't want to break/accidentally prevent in the API design)

From my perspective, Delivered is clearly in 3, Acknowledged is less useful, but could be in 2

**Comment by mwelzl** [comment]
I'd like to see a good argument for usefulness for everything we add. I think "Sent" is settled - this relates to controlling the send buffer and is clearly necessary for applications that want to have control over what they send as long as possible.

For "Acknowledged" and "Delivered", why are they useful at all? What are examples of what an application can do with this information?   Sorry, maybe I'm missing a big obvious piece here!

**Comment by gorryfair** [comment]
I'm still quite concerned about this primitive - it seems to create cases where someone coding could believe a message has been delivered to an App because the transport tells it something. That I think is bad. The App should use it's own protocol to decide the data has reached the remote. I could see corner cases where someone may wish to invent a new protocol that does remote buffer management, but really having seen several of these in the past - I'd need strong proof that this was a general need and had significant advantage - if it's buffer management, I'd prefer the sender to express the "use case" to the stack and the stack manage this, not some application-visible signal.

**Comment by tfpauly** [comment]
Agreed that a delivered event doesn't seem like a good idea. If nothing else, it can end up breaking a truly end-to-end model. How does the TAPS system know that the data really was delivered? To whom was it delivered? Even if the protocol has ack'ed data, how do we know that wasn't just a proxy that read the data? Etc, etc. At the end of the data, data being consumed by whoever the application thinks of as the remote endpoint is a matter that can only be decided by the application based on some higher level of signaling.

**Comment by philsbln** [comment]
I agree to @gorryfair that we need to make clear that `sent` does really mean nothing but somehow handled by the local transport system.

Whether to include `acknowledged` and `delivered` really depends on what we see as our goal: Is it to build a flexible API for what is available today or to design for the mid-term future. If the target is the latter, we should at least include `acknowledged`, as it is implementable on top of TCP and allows the application to estimate the bytes in flight for buffer- and rate limit.

I fear that we will get a lot feedback stuff we could enable (like `acknowledged` and `delivered`) and should find a way to deal with it in a way that we can acknowledge this stuff and show that the TAPS API can be extended to incorporate these features if needed in the future.

**Comment by mwelzl** [comment]
For buffer limiting, we have what we need already using the Sent callback. I can see the possibility of optimizing things based on an estimate of the packets in flight... but I'm sceptical about this being the right design - are you going to let applications do things that we'd better do inside the transport system?  E.g. if you're thinking of interface choice / load balancing decisions based on the packets in flight, isn't this something that the transport system should do, not the application?

Plus, at least according to the spec, this is *not* implementable on top of TCP. There may be implementations that allow it but it's not spec'ed as a standard behavior.

**Comment by britram** [comment]
Closing with apparent consensus not to do this.
