### ISSUE TITLE
Need relative ordering of API events

### ISSUE THREAD

**Issue by JonathanLennox** [taps-api/drafts#155]
The API document needs to specify the relative timing and ordering (i.e., for appropriate thread models, the threading properties) of events.

E.g., I think it should be guaranteed that a connection's Received<> event isn't called until its initiating event (Connected<>, ConnectionReceived<>, or RendezvousDone<>) has finished processing; and only one Received<> event is invoked at a time for a given connection, with the events being invoked with the appropriate logical order is required by the connection semantics.

Similarly, only one of a connection's Sent<> events should be invoked at a time.  However, I don't think there needs to be any restriction against Sent<> and Received<> being invoked simultaneously on the same connection.

No other events should be received for a connection after Closed<> or ConnectionError<>.

For different connections, It should be allowed for their events to be invoked simultaneously, even if the connections are entangled with each other.

**Comment by JonathanLennox** [comment]
One particular consideration that came up in the May 16th call is that this last event (presumably Closed<> or ConnectionError<> or Aborted<> or whatever) needs to be enqueued to be executed after previous callbacks complete, rather than being executed synchronously on the stack of another callback.

**Comment by britram** [comment]
fixed by #195
