### ISSUE TITLE
API needs a way to know that Close() or Abort() are done

### ISSUE THREAD

**Issue by JonathanLennox** [taps-api/drafts#156]
An application needs a way to know when its Close() or Abort() call is complete, guaranteeing it won't receive any further events on the connection and all current event processing is done.  This is necessary so the application can clean up any application state related to the connection.

Note that in a multi-threaded environment, events can be executing on other threads at the same time that the Close() or Abort() call is called; in addition, an application can potentially call Close() or Abort() from within an event processing function itself.

**Comment by britram** [comment]
The intention (in the API) is that the Closed<> and Aborted<> events fire after these are complete, whether the close or abort was locally or remotely initiated.

**Comment by britram** [comment]
fixed by #195
