### ISSUE TITLE
Write §3.2 Role of system policy

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#16]
Describe the relationship between application preferences, system policies, and implementation defaults for connection management.

**Comment by tfpauly** [comment]
Added some initial text in the document; please edit/change as needed.

**Comment by karlgrin** [comment]
@tfpauly Complemented and revised text.

**Comment by karlgrin** [comment]
Currently, it says in Section 3.2 that "In general, any protocol or path used for a connection must conform to all three sources of constraints. **Any violation** of **any of the layers** should cause a protocol or path to be considered ineligble for use. Isn't this a bit too stringent? Shouldn't there be some kind of scoring involved in the policy resolution process that ranks Protocol Stacks. The ranking would then determine how the racing is conducted.

**Comment by tfpauly** [comment]
I think that the flexibility comes in if the policy of the system or requirements of the application are flexible—prefer versus require. But if the application prohibits or requires something, or the system policy does, that must not be broken to avoid violating policy (which sometimes is a legal issue for the system).

**Comment by tfpauly** [comment]
Thanks for your update! I tweaked one word back (the implementation being responsible for balancing all three items (system policy, application requirements, and defaults), rather than system policy itself).
