### ISSUE TITLE
Write §4.5 Establishing multiplexed connections

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#17]
Describe how multiplexing impacts connection establishment—especially opening a new flow or stream on an established connection.

**Comment by mwelzl** [comment]
Hi, I could write some text for this based on minset - and I could also write some more text for the section on SCTP.   E.g., to support priorities between streams, in SCTP, one really should use message interleaving.

**Comment by tfpauly** [comment]
Assigned! I'll also want to make sure we address the style of opening new streams for QUIC or HTTP/2 as a transport.

**Comment by mwelzl** [comment]
Thanks!  (and: of course, re: QUIC / HTTP/2)
