### ISSUE TITLE
Add architectural section on protocol equivalence as it pertains to racing

### ISSUE THREAD

**Issue by chris-wood** [taps-api/drafts#172]
And add a subsection specifically for security protocols. Determining what security protocols (and configurations) are equivalent is nontrivial and incredibly important if we are to race, e.g., TLS and gQUIC.

**Comment by gorryfair** [comment]
I think the racing/gathering section needs a tiny little explanation text and this seems reasonable to add - if you add to this section, can you also make sure it mentions something of the terms "policy" and "cached state" as a part of this update?

**Comment by chris-wood** [comment]
@gorryfair yes, will do!

**Comment by chris-wood** [comment]
Addressed by #199.
