### ISSUE TITLE
Do we need a "send acknowledged" event?

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#174]
The discussion about the "immediate ACK" in SCPT (issue #90) raises the question whether the application should be notified about the message being acknowledged.
I guess this has to get along with a protocol selection property (require/prefer/ignore) but is hard to implement for protocols like TCP.

**Comment by mwelzl** [comment]
My reaction speed is a far cry from "soon", sorry!!  Anyway, reading issue #90 again, I think I explained enough stuff in detail there: if we decide to leave buffer handling to the transport system (which I think we now decided), leading us to remove "immediate ACK", I can't see why we should have functionality to tell an app that a message has been ACKed. This is all a matter of transport-system internal buffer management, I'd say.

**Comment by philsbln** [comment]
When thinking about new transports, I think this might be a useful thing - but not for discussion now - re-opening it with milestone "Science Fiction"
