### ISSUE TITLE
ARCH: Background/intro inadequate

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#189]
To me the document is in very good shape, but there are several things that just appear, and a few short paras and maybe a simple picture could help avoid people giving-up before they know the document is useful to them.

We seem to not introduce it nicely, I'd suggest:
+ This isn't scarey (draw a simple familiar figure to start our story, that the reader immediately recognises)
+ Sockets v Streams ... we speak of messages, let's explain early that they ae all you need for any app.
+ Events ... we know these are "nromal" - but let's say we provide an eevent-driven interface. it would even be worth saying why thsi is much better (Tommy - Apple have been doing this from the start, can you perhaps say why it is beautiful?)

Comments follow:

Section:  Background.
- The last part of this section suddenly introduces messages. I know it is just an example, but readers may be already looking here at whether this is an interface to TCP or UDP or something else ... and I think we do not really tackle that earlier enough. One way to help that would be to draw a diagram that looks something like this, in this section:

  +-----------------------------------------------------+
  |                    Application                      |
  +------------------------+----------------------------+
                           |
  +------------------------|----------------------------+
  |           Transport  Services  API                  |              
  +------------------------|----------------------------+
                           |
  +------------------------|----------------------------+
  |         Transport   System  Implementation          |
  |                                                     |
  |        e.g.,  UDP, TCP, SCTP, DCCP, QUIC, ...       |
  +------------------------|----------------------------+

  +------------------------|----------------------------+
  |              Network Layer Interface                |
  +-----------------------------------------------------+

And the say that the Transport  Services  API provides message-oriented communication using transport protocols (e.g. UDP, TCP, etc). I'd also mention the words /data transfer/ somewhere.

Providing a simpler earlier diagram may also be slightly easier on the new reader.
---
In the same way, the intro should explain a little of the idea of /events/ - common enough to some, but may be unexpected for a new reader.

**Comment by gorryfair** [comment]
I suspect you're already writing this sort of approach:

I think it would be super nice if the background/intro text clearly had a para expalining that this is a call-back based API. I do suspect that many people coming to this will be atrracted because the new API is simple and provides a more modern interface. The rationale for why we design it to enable multiple transports, etc, is the "detail inside the engine" the fact it delivers what they want is the first point to make:-).

**Comment by britram** [comment]
@tfpauly does #236 close this issue?

**Comment by tfpauly** [comment]
@britram Yes, I think so.
