### ISSUE TITLE
Adjust status once it's clear...

### ISSUE THREAD

**Issue by mwelzl** [taps-api/drafts#192]
currently it's Informational

**Comment by britram** [comment]
ISTM this should be Informational for Arch and Impl, and PS for API. I suspect we'll want to spend a little time discussing this on the agenda in Montreal.

**Comment by gorryfair** [comment]
IMHO this  API really needs to be PS -one useful point is this can be cited by other organisations.

I am not sure if arch should be PS to allow it also to appear outside the ietf ... but that’s probably clearer when we understand the final shape. Imply is info.

**Comment by tfpauly** [comment]
Agreed that we should do:

- Architecture: Informational
- API: Proposed Standard
- Implementation: Informational

**Comment by mwelzl** [comment]
From https://datatracker.ietf.org/meeting/102/materials/minutes-102-taps-00

Hum for interface:
    Standards: (strong hum) (+1 from meetecho)
    Experimental: (small hum)
No hum for informational

Hum for architecture:
    Standards: (strong hum)
 Informational: (light hum)

Hum for implementation:
   Informational: (strong hum)
   Other track: (no hum)
