### ISSUE TITLE
Clones and entanglement

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#202]
I previously agreed with this:
There is only one Protocol Property that is not entangled now I don’t. 

Here is why.... I think the default for any per message action is independent to each cloned entity. Niceness is one aspect - relative priority and DSCP may fit here. So also I argue does checksum coverage. Is it possible a flow is cleaned and one clone used for video, one for audio? They may well present different coverage needs. Niceness:DSCP: coverage: TTL - for those datagram protocols where this is important.
- Conversely : If all packets of clones follow the same path, you would NOT wish to separately manage the max packet size, or such path detail; these are shared by all clones: maximum size: time for aborting;
- Alas this also makes me ask a more fundamental question: is capacity profile inherited the same by clones - and how do such things actually relate when the  multistream mode is used - to me this more tightly binds the steams. On this,  I would value opinions - because for udp I can see both ways, but ietf outputs suggest that for tcp and sctp there should be one capacity (dscp phb group if using this ) per flow/association, and I expect that also applies to quic.
—-

**Comment by mwelzl** [comment]
First, I'm not sure I fully understand this - is the problem that so many properties *are* entangled, or is it that one isn't?  IIUC you say "the former". 

Now note, cloning and entanglement just represent multi-streaming. So a lot of things naturally must be "entangled"...

The capacity profile is configurable per-message, so that shouldn't be a problem.

**Comment by gorryfair** [comment]
Aha - I started things when I have very limited connectivity. Sorry. So trying to brief:

I think there is more than niceness that is not entangled. 

I think I need more clarity on what it means to be cloned but not allow multi streaming.

Gorry

**Comment by mwelzl** [comment]
Ok - more than niceness that is not entangled is fine, but mostly these will be things (I suspect) that can be adjusted per-message anyway, so why worry about them...

We're currently undergoing re-organization; I think considering something like this, which essentially means going through the properties one by one, is better done after Montreal.

Regarding being cloned but not allow multi streaming: that combination doesn't make sense to me.

**Comment by gorryfair** [comment]
On this we seem to agree? And I think the test needs edit.

- all per message actions are not entangled?
... niceness is one example. To me the text needs improved, to be clear there are others.

- check what is intended with multi streaming

Gorry - still on a poor link from a phone.

**Comment by mwelzl** [comment]
Agreed!
