### ISSUE TITLE
Re-Structure Transport Properties

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#208]
After getting a better understanding, we need to push the properties in a next-step structure.

We actually agreed on three kinds of Properties:
 - Selection Properties (stuff that effects the pre-connection)
 - Connection Properties (stuff that effects the connection)
 - Message Properties (stuff that effects the individual message)

Each of them can be set on the objects above in the list and are used as defaults then.

Each property will be marked as specific (clear protocol specific meaning) or generic (needs implementation and protocol specific meaning, but otherwise consistent behavior).
More fancy Intents are deferred to another layer above the TAPS system.

Selection Properties requesting per-Message behavior are just cross-references.

**Comment by britram** [comment]
see the resolution to #218; I would also suggest moving protocol selection properties up to a section closer to the pre-establishment phase section of the document. I didn't see a response from @philsbln today so I didn't do this, not wanting to collide with any work you may have in progress. I'll probably get cycles to do this again on 15.10. though if you like; I would like to get these out for -03.

**Comment by philsbln** [comment]
Fine with me – please retain data types when moving and leave overview in Section 12 analogous to the other properties.

As soon as I get spare cycles again, I will turn Section 12 in a proposal for a registry

**Comment by britram** [comment]
Taking the token here. Note that Section 12 will largely be replaced a list/table showing relationships among properties and containing references back into the document where each property (split by class) will be defined. "Classification" will then disappear in the text, being implicit in the document structure.

**Comment by britram** [comment]
will keep this open until there's consensus on the restructure; removing assignments and milestones to reflect that this is the state we'll have for BKK though.

**Comment by mwelzl** [comment]
I think we had consensus before and in BKK, so I'm closing this.
