### ISSUE TITLE
Be explicit about what the interface defines and does not define

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#211]
Now that the document is targeted for the standards track, its purpose (i.e. what exactly it standardizes, and what it does not) should be made clear. This is made a little more difficult because, as an abstract API we intend to be implementable in any reasonable language (i.e. no brainfuck kthxbye), 

Here's what I think the scope is:

- message-orientation
- asynchronicity of event and reception
- asynchronicity of resolution and initiation
- the "shape" of the API: objects and events, and interactions between them, with a RECOMMENDATION that you use the same names ("unless this facility is implemented in terms of a networking interface that already has different names or naming conventions for equivalent objects" or something like that).
- an MTI set of selection, connection, and message properties, and definitions (though not names) of these properties. 
- a larger fully defined set of selection, connection, and message properties, such that if a system implements a given property it must implement it as described.

**Comment by csperkins** [comment]
Why would we not want to make a recommendation on the names of properties? We'll need to name them in the drafts anyway, if we're to cross-reference them from elsewhere, and at that point there's no benefit in not recommending re-use of those names in concrete API implementations.

**Comment by philsbln** [comment]
I think providing consistent naming across different implementations will be a key argument for the adoption of the abstract interface. The strongest argument for sticking to BSD Sockets is that they somehow look the same on all platforms. We should not miss the change to at least give recommendations about how to name the individual objects and properties. Implementations can and should extend and divert from it where it makes sense, but recommending names should help the individual APIs look at least similar.
