### ISSUE TITLE
P* discussion

### ISSUE THREAD

**Issue by mirjak** [taps-api/drafts#218]
A bunch of the taps authors had a breakfast meeting at some point in Montreal and while I wasn't able to find any minutes or notes about this, I do think we reached some kind of agreement on some parts of the P(arameter|roperty|referenc) discussion. Here is what I memorize:

- There are no P*s that can be per connection and per message. Everything that is currently scoped for connections and messages should be split up into two different things with different names because it is not the same.

- All P\*s that a scoped for connections also are in scope for a preconnection, however, (1) this is not true the other way around, and (2) preconnection P\*s are rather "preferences" and connection P*s are either configuration, meaning you can change them during the life of a connection, or fixed settings that you can only retrieve for your information but have been set in the preconnection phase.

- Protocol-specific P* are special and kind of "free-form"/implementation specific. I think we actually need to further discuss how to implement/use them at some point (Do I need to specify a set of protocol P* for every possible protocol at preconnection time or does the protocol P* I specify impact my protocol selection? I think it's a bit confusing for the user if you can specify a bunch of e.g. TCP P* and then get a QUIC connection back...) but I guess that's a separate issue...

- Most things that are currently classified as intents are probably not part of taps but might be implemented in a high (shim-)library that can translate these intents into P*s.

Does that sound about right? Any further thoughts?

**Comment by mirjak** [comment]
Also, I guess there is also something like system configuration which I guess we have mostly ignored so far...?

**Comment by mirjak** [comment]
Related to #208

**Comment by tfpauly** [comment]
+1 to not sharing P* between Connection and Message

Yes, this seems like a good summary!

**Comment by theri** [comment]
Yes, I think this and #208 is what we agreed on.
Also, I wrote down that we wanted to make sure every generic property has a deterministic mapping to a specific protocol behavior (in the implementation draft?).

I hope we can agree on whether to call them Properties or Parameters soon, too - P* confuses me...

**Comment by mwelzl** [comment]
Thanks a lot Mirja for this summary. Clearly you had a constructive meeting - I agree with all these outcomes. Just one thing, about protocol-specific properties: there are in fact a couple of things in our whole design that occasionally make me stop and wonder if we're over-specifying things - and this is one of them. I mean, yes, implementations can allow their users to set a TCP-specific option for the case the system picks TCP. There's no way we could stop people from doing this, yet it's probably nothing that we should prescribe or (IMO) even recommend. So, can we just stop talking about this, and simply remove the text talking about this being a possibility?

@theri: Properties!  This is now used all over the place in the interface draft and I just think it's a better choice than parameter. A parameter is what you give to a function call ("action" in our terminology), whereas messages, connections etc. have properties. A property could be configured via a parameter of an action.

**Comment by gorryfair** [comment]
+1 -> P=Properties

**Comment by philsbln** [comment]
In my opinion, Properties is the least confusing term we can choose. 

Despite that, I have no strong opinion on how we call this thing - but not P*, please!

P.S: I like it, that Properties can be a used as parameters to the protocol and path selection and therefore express preferences of the application.

**Comment by mirjak** [comment]
I was actually thinking about calling things we do to the preconnection a preference and things we can configure for a connection a property (or just configuration?). Is that too confusing or more clear?

**Comment by mwelzl** [comment]
I like it! "Preference" for preconnections is really nice. For the latter, I prefer property over configuration.

**Comment by mwelzl** [comment]
Ok - I agree, sorry.

**Comment by mirjak** [comment]
I guess it's easy to rename to data type.

**Comment by theri** [comment]
I agree with @philsbln that just calling them Properties is least confusing, and that Preferences is a data type, not a classification.

**Comment by abrunstrom** [comment]
I thought calling them Properties was one thing we had agreed on :-) I am still fine with that.

**Comment by tfpauly** [comment]
+1 to Properties

**Comment by britram** [comment]
+1 to Properties, though since we're talking about it I think "Message Context Properties" (formerly Send Properties) should probably just be Message Properties (or, if you like for purposes of this discussion, M*P* :wink:

**Comment by philsbln** [comment]
Ok - lets wrap this up:

 - We have rough consensus for calling P* ``Properties``
 - We should shorten ``Message Context Properties`` to ``Message Properties`` (the document uses both terms interchangeably at the moment)
 - Our primary structuring criteria for Properties is when they can be specified – This leaves us with ``Selection/Connection/Message-Properties``
 - Other attributes of properties are annotated in the header of the properties or described in the text if necessary: 
    -  The Data-Type
    -  Whether they are ``Protocol-Specific (Connection) Properties`` or ``Generic (Connection) Properties``
    - What selection process, i.e., (Path/Protocol-Selection, they effect
    - Their meaning and whether they are interpreted.

If there is no opposition for this wrap-up, I'll try to fix these with the next parts of the restructuring.

**Comment by britram** [comment]
@phlsbln agree broadly but i'm not sure that the selection properties appear in the right place in the document. I have some cycles on a train today to try to do this compression/re-org, so I'm happy to do this unless you're already in progress on this one.

**Comment by britram** [comment]
oops bad tag of @philsbln ^^ see above

**Comment by philsbln** [comment]
Still on my todo list, but I have no spare cycles till end of October. 

The idea of moving the selection stuff came also across my mind several times.
Go ahead and move the section, I will pick up from where you finish.

Sorry for the late reply.

**Comment by mwelzl** [comment]
I believe that was all planned to finish by BKK, and people seemed fine with the structure in BKK. So, I think this is done and I'm closing the issue.
