### ISSUE TITLE
WTF is a PreconnectionBinding?

### ISSUE THREAD

**Issue by mirjak** [taps-api/drafts#219]
section 6.3 (Rendezvous) has the following line:

PreconnectionBinding := Preconnection.Resolve()

If i read the text correctly, I'd propose to change this to 

Preconnection<> := Preconnection.Resolve()

**Comment by csperkins** [comment]
Agree with the change. `PreconnectionBindings` are new `Preconnection` objects derived from the initial `Preconnection` by a process like ICE. E.g., once the resolve call has done a STUN exchange to find the external address of a NAT you're behind, you'll get back an object that represents that external address.
