### ISSUE TITLE
Write §7 Implementing Termination

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#22]
Explain how to handle application-intiated termination, and protocol stack-initiated termination. Explain impact of terminating a stream on a multiplexed connection.

**Comment by mwelzl** [comment]
I wrote some text here. I'll leave the issue open so others can check if this is missing something. If you think this is good enough, please finish it off by removing the listed items / adjusting the text a little, and close this issue.

**Comment by tfpauly** [comment]
Looks good, will clean up in editorial pass.
