### ISSUE TITLE
Write §8 Cached state

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#23]
Explain cached state for both protocol states (TLS, DNS) and historical performance.

**Comment by tfpauly** [comment]
Added an initial pass to the document; feel free to edit/change as needed!

**Comment by chris-wood** [comment]
I pushed a small change -- let me know what you think!

**Comment by tfpauly** [comment]
Looks good to me, thanks!

**Comment by karlgrin** [comment]
@tfpauly I think I was supposed to write this section, however, it seems in large part to be completed. Would like to discuss what is missing. Personally, I think 'cache lifetime' is one issue missing.

**Comment by abrunstrom** [comment]
@karlgrin, feel free to add to the text.

**Comment by tfpauly** [comment]
Great point about cache lifetime, yes.

**Comment by karlgrin** [comment]
@tfpauly Written some text on cache lifetime, however, I believe this needs to be discussed further. I don't really know if any more concrete guidelines could be given. Your input would be much appreciated.

**Comment by tfpauly** [comment]
@karlgrin Thanks! I agree with your general approach in this text. I moved the order of the sentences a bit, but other than that I think this is good for -00.
