### ISSUE TITLE
Write §9 Specific Transport Protocol Considerations

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#24]
Explain specific concerns for given protocols, likely based on survey and minset. Anything from minset that isn't covered by earlier sections or the API explicitly should be mentioned here.

**Comment by tfpauly** [comment]
Written in draft.

**Comment by abrunstrom** [comment]
@tfpauly thanks for filling this in. I do not understand the part about partial messages and marking the message complete for TCP though. I do not think we have the matching parts in the API? Also do not understand the part about "closing the sending stream" for TCP.  Close will currently close the connection in both directions.

**Comment by tfpauly** [comment]
Updated the text to indicate that the Close does send a FIN (without saying this is specifically a half-close), and explained how multiple parts of the total message are sent.

**Comment by tfpauly** [comment]
I'll double check the API to make sure it has the right send parameters; if not, I'll open an issue.
