### ISSUE TITLE
Editorial: Why own subsection for "Transport Security Equivalence"?

### ISSUE THREAD

**Issue by mirjak** [taps-api/drafts#261]
I think the text in "Transport Security Equivalence" could also just be added to the bullet point above as done for the other requirements as well. I don't see why we need an own subsection there...

**Comment by mirjak** [comment]
Btw. maybe "Transport Stack Equivalence" should be a subsection of "Transport System Implementation Concepts"?

**Comment by tfpauly** [comment]
Agreed for both points—I just moved the "Transport Security Equivalence" section into the bullet point 3 in the stack equivalence, and made that part of the implementation section.
