### ISSUE TITLE
Cross Referencing between Resolving Remote Endpoints and Connection establishment

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#27]
Resolving Remote Endpoints may result in different stack configurations - add reference to Connection Establishment and how to retrieve the protocol stack actually provided

**Comment by tfpauly** [comment]
- Isn't resolving remote endpoints a sub-step of Connection Establishment

- Yes, the resolution can definitely lead to different stacks. It's a good point that you need to be able to introspect what you actually used to connect.

**Comment by philsbln** [comment]
- I wrote in the respective resolving section that the actual resolving MAY be deferred until connection establishment (might also be done immediately to save time) – so Yes and No
- Still thinking whether we should rename "Resolving Remote Endpoints" to "Specifying Remote Endpoints
- I am not sure whether this is "just" introspect or something more explicit, e.g. a parameter to the connection event. 
   - If we can flag framers with protocols/features in pre-establishment, I think introspection is sufficient
   - If we add framers _after_ connection establishment, we should make the protocols chosen more explicit.

**Comment by csperkins** [comment]
I suggest that "specifying a remote endpoint" is a different operation to "resolving a remote endpoint". You could specify an endpoint using a name that you can't directly connect to (e.g., a DNS name), and that may need to be resolved to find usable, concrete, names that can be used for a connection (e.g., resolving the DNS name to a set of IP addresses).

Depending on what a name resolves to, might affect how the connection is established. The resolution conceptually happens before connection establishment, although a practical implementation might combine them.

**Comment by philsbln** [comment]
So then we rename the Section to ""Specifying Remote Endpoints".

I suspect there should be no "resolving a remote endpoint" in the API because this is an implementation issue and not directly exposed though the API

**Comment by britram** [comment]
+1 to calling this "specifying endpoints".

It seems like there should be something either here or in the references about certain "kinds" of endpoint specifier / transport parameter combinations being necessary for each kind of initiation. The split between these requirements might be enough to turn Endpoint back into Remote and Local, but I'll wait for all the pending issues on the API to be closed, and if this still bothers me I'll file a new issue.

**Comment by philsbln** [comment]
Ok – this issue has become a collection of various resolving issues that have been fixed now.

Closing this for now and creating Issue #47 for stack and pseudo-transport issues
