### ISSUE TITLE
Prioritization among Transport Parameters in the API

### ISSUE THREAD

**Issue by theri** [taps-api/drafts#28]
(How) Should an application be able to prioritize between Transport parameters, especially Protocol Selection Properties?
Section 5.2.1 currently defines Reliability and in-order delivery as "strict requirements", since not providing this when an application depends on it would be bad, as explained in 5.2. Other properties are mostly "not a strict requirement".
Now we could additionally have an explicit prioritization by the application for the "non-strict requirements", and/or to let the application specify that it absolutely requires a certain property, even though it is marked as "not a strict requirement" in the draft.
What do you think?

**Comment by tfpauly** [comment]
A prioritization scheme could get very complicated =) If an implementation needs that, that may be better as an extension?

What you can do is have different levels of requirement:
- Require (fail if you can't do this)
- Prefer (try to do this, but don't fail if you can't)
- Avoid (try not to do this, but don't fail if you can't)
- Prohibit (fail if you can't not do this)

The path you select is the one that meets requirements and prohibitions, and the most number of met preferences/avoidances. That's worked for us =)

**Comment by theri** [comment]
Yes, different levels of requirements is what we were aiming for. :)
I just discussed this with Philipp and we propose the following:
Instead of passing properties in the Create() call, make a SetRequired(),SetDesired() and SetIntention() call which sets these properties. 
Avoid and Prohibit would then be a SetDesired() or SetRequired() of the negated property, so we would add an "Unreliable Data Transfer" property next to the "Reliable Data Transfer". Not all properties make sense in their negation, e.g., "I prohibit having the option to disable the send checksum" is not a property I would add.
Does the above make sense to you? In that case I'd update Section 5.2 accordingly.

Note that this could lead to a situation where an application requests "Reliable Data Transfer" only as Desired, not as Required. This might even make sense in case the application has a congestion control mechanism of its own, but would also be okay with using TCP. On the other hand, I'm not yet convinced that we should get rid of the inherent prioritization of, e.g., Reliability over other properties.

**Comment by abrunstrom** [comment]
I am not fully convinced about splitting this up in multiple calls for required and preferred properties. I think it may be simpler to just allow setting a property to required or preferred in the same call.

If required or prohibited properties can not be met that represents a failure. How to deal with preferred properties I think is up to the implementation of the transport system and may also depend on configured policies. I do not think the application should be able to prioritize between properties, beyond setting requirements and preferences.

**Comment by britram** [comment]
> I am not fully convinced about splitting this up in multiple calls for required and preferred properties. I think it may be simpler to just allow setting a property to required or preferred in the same call.

+1. this seems like a... property of the property. (we'll want better terminology, of course)

**Comment by philsbln** [comment]
Theresa talked about that for quite a while.

First, I want to make sure that we agree on some things:
- The same property can be specified with different "priorities", e.g., "Unreliable Transmission" might be "preferred" or "required"
- Rather than "required x" and "required that not x", we have two properties "x" and "un-x"

I am of the opinion that SetProperty($prio, property, value) and  SetProperty$Prio(property, value) with $prio in (required, desired, intent) only differ in terms of syntactic sugar.

The advantage of the latter is that it feels less awkward if used with a dictionary containing (property, value) pairs instead of using a bunch of SetProperty calls.

**Comment by theri** [comment]
I've thought about this a bit more I think assigning a "priority" (required, preferred, avoided, prohibited) to each property, with sensible default priorities, is also a good way to do this. This way, we avoid having to duplicate properties as "x" and "un-x", which may be confusing.
However, "priority" sounds too much like a more fine-grained differentiation, which I agree would be too much for this API, and also it doesn't imply that the value of this property can also be "avoid" and "prohibited". 
I'm trying to come up with a better term. Maybe something more along the lines of "purpose" or "meaning", i.e., "how to interpret this property"? But that's confusing as well.
Alternatively, if we have only one call to set properties, we could have different parameters within the call, like Connection.SetProperties(require=[...], prefer=[...], avoid=[...], prohibit=[...]). Then we don't have to name whatever is the general term for "required", "preferred", "avoided", and "prohibited".

**Comment by tfpauly** [comment]
Yeah, let's not use Priority for this—if anything, it should be Preference.

I think of, for path properties, an application setting its preference for Cellular interfaces. "I require a cellular interface type", "I prohibit a cellular interface type", "I avoid cellular interface types".

Also, note that these shouldn't necessarily be set directly on the Connection. We use a separate parameters/properties object, so you could configure a set of properties once, and then apply it to multiple connections if needed.

**Comment by mwelzl** [comment]
I like Preference (FWIW). I'm still a little worried about the complexity of all of this...

**Comment by tfpauly** [comment]
Agreed on the complexity. I think the approach for the API should aim to be as simple as possible. Having an enumeration of how to have a preference is useful as a tool for writing the API for various Protocol Selection and Path Selection properties, but the basic set of these properties should be kept tight and small for the first cut.

**Comment by abrunstrom** [comment]
Very much agree on the issue of complexity and keeping the basic set small! An implementation can then add as many properties as it wants as long as it has matching policies and machinery to do something useful with them.

**Comment by philsbln** [comment]
Ok - then let us get the framework right and just have a very basic set of properties here.
- One basic operation --- connection.setTransportParameters(preference, parameter, [value])
- A very basic set of parameters to get an impression how this is used
- Make explicit what can be set in pre-establishemnt and what afterward
- Merge / Streamline with other mechanisms (e.g. specifying remote endpoints)
 
Afterwards we can externalise most parameters derived from minset and socket intents into a separate document.

**Question to all:** should we use methods of a Connection to set-up everything in pre-establishment or should we have an endless list of stuff to pass to the Connection constructor?

**Comment by mwelzl** [comment]
I like the plan up to the part where it says "...into a separate document". Either way we need to agree on the parameters.  Putting the parameters in a separate document doesn't help - in my opinion the current structure is really good!  Let's please not start creating other documents now!

One basic operation to set all the parameters seems good; we have the same in NEAT  (we call it "setProperties", and then there's a list of properties that this can set; the property list isn't contained in the draft https://tools.ietf.org/html/draft-fairhurst-taps-neat-00 - generally, I think the related public deliverable is a better reference, it's slightly more complete:  https://www.neat-project.org/wp-content/uploads/2015/05/D1.3.pdf  ).

About the "endless list of stuff": the list will be a bit shorter when I'm done with it  :-)   but... well I guess my vote goes to giving it all to the constructor.

**Comment by tfpauly** [comment]
Agreed that we don't want a separate socket intents document (also, we really need to ditch the name socket-intents, since sockets aren't relevant here).

We should define the basic, tight set of properties we want and have them in the main API document. And also define how to extend them.

**Comment by philsbln** [comment]
- After my or Theresas next pass, it is socket intents will be gone and replaced by "application intents" - already agreed on
- Regarding the property descriptions:
   - I don't think the Application Intents are not the majority of properties - there are much more derived from minset. 
   - The question is whether we want to keep them here and in-line, appendix or in a separate document. I fear when we have a reasonable description, this will become quite lengthy.
       - whether they are path selection / protocol selection / both aforementioned / application intents / protocol tuning properties. 
      - Whether you can require them
      - In which phase they can be use
- I don't like having a "property container object" which we can pass to the constructor, neither do I like passing all properties as VA_ARGS. – Therefore connection.setProperties() feels right.
- Passing "endpoint objects" to the constructor also feels right. 
- If we want to normalise the style of the API, either of them has to change.

**Comment by theri** [comment]
I agree that the current structure is good and would be against a separate document. Rather let's specify the most important ones. 
As the audience for the API draft would be application developers, let's specify what they would need to know to use this API, and put implementation considerations etc into the implementation draft. I hope by doing this we can keep it short enough.

About the call structure, I prefer having one call that sets all properties at once to several calls which each set one property. I'm fine with a container object, since it is easier to clone and modify than a list.

**Comment by mwelzl** [comment]
I like the idea of an appendix. What about presenting and discussing (as concisely as possible, of course) all the parameters that we want to have in the main text, and then adding an appendix that clarifies in which phase they can be used, whether they can be required, etc., with a table?

**Comment by theri** [comment]
Sounds good to me. :)

**Comment by theri** [comment]
Drafting the appendix.

**Comment by theri** [comment]
Added a first version of the preferences table.
The current values are just a suggestion - first I was sure that prohibiting to control checksum did not make any sense at all, then I thought how it might affect an application if the other side was allowed to control checksum coverage and how maybe an application developer would like to prevent that. Feedback in appreciated. 
If you agree with the current preferences in principle, we could also close this issue, I think.

**Comment by philsbln** [comment]
I like the table a lot.

I see a problem with not being able to change Path Selection Properties if we want to support all use-cases of connection migration and multipath – open Issie #38 for that.

**Comment by britram** [comment]
+1 to I'm a fan of the table; see also a comment in #34 about how to realize this in the API.

Closing this since it seems we've moved on to other issues.
