### ISSUE TITLE
Fix "Close" and "Abort"

### ISSUE THREAD

**Issue by mwelzl** [taps-api/drafts#30]
We had long discussions about "Close" and "Abort" in NEAT, considering what these primitives mean for TCP, UDP, SCTP, *and* SCTP streams. As these definitions stand, they are not right - the "Close" definition implies support of half-closed connections, which aren't very useful and not supported by all protocols. The "Abort" definition indicates that the remote endpoint is notified, but that should also (or, "no less") be the case with "Close"; the difference can really only be that "Close" will try to deliver remaining data that a sender has in its stack, whereas "Abort" won't. We can discuss these at length if you want to re-iterate... I think I have slides from a project meeting summarizing the discussion.

Anyway, My proposed definitions are:

Close is the action an application may take on a Connection to indicate that it no longer intends to send data and will not be willing to receive data, and that the protocol should signal this state to the remote endpoint if applicable.

Abort is the action an application may take on a Connection to indicate that it no longer intends to send data and will not be willing to receive data, that it does not need the transport system to continue trying to deliver any outstanding data, and that the protocol should signal this state to the remote endpoint if applicable.

**Comment by tfpauly** [comment]
I like these new definitions a lot! I think they better express what we actually do, as well. I'll incorporate into the document.

**Comment by tfpauly** [comment]
Incorporate into the architecture doc!
