### ISSUE TITLE
[architecture/§3.1] Common APIs for common features

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#40]
Section 3.1 of the architecture draft says:

```
   Any Transport Services API must expose the basic set of transport
   networking features.  This implies, at a minimum, the ability to use
   the equivalent of both TCP and UDP socket interfaces.
```

Should "expose the basic set" be "expose the distilled minimal set of features offered by transport protocols [I-D.ietf-taps-minset]" or is the basic set intended to be different?

I also suggest removing "This implies, at minimum, the ability to use the equivalent of both TCP and UDP socket interfaces" since it's covered in Section 3.3.

**Comment by tfpauly** [comment]
Fair point that the TCP/UDP coverage is already specified in 3.3. I'll remove it in 3.1.

And yes, the basic set is the minimal set (and if there's any difference, let's edit the minimal set)

**Comment by csperkins** [comment]
I'm working on this now, so if there's agreement I can make the edits.

**Comment by tfpauly** [comment]
That would be great, thanks!
