### ISSUE TITLE
[architecture/§3.3] basic transport protocols

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#41]
In section 3.3 of architecture "all implementations should offer sufficient APIs to use basic transport protocols like TCP and UDP", should this be "...to use the distilled minimal set of features offered by transport protocols [I-D.ietf-taps-minset]"?

We should be consistent about what's the base set of protocols (see also #40)

**Comment by tfpauly** [comment]
I agree that this is referring to minset, however, I was trying to capture what came up several times in discussion that it should be clear that this encompasses TCP and UDP. Mentioning TCP to allay the concerns that this interface could only be for higher-level framing, and mentioning UDP to allay the concern that unconnected datagram interfaces are not considered. How about mentioning both, i.e.: "this is minset, which by the way covers the same thing you're used to in TCP and UDP sockets, plus more".

**Comment by csperkins** [comment]
Sure, makes sense.
