### ISSUE TITLE
How to set / query protocol properties after establishment

### ISSUE THREAD

**Issue by mwelzl** [taps-api/drafts#46]
Hi,

This needs text - the fact that one can change properties in established state is somewhat hidden in the API doc, but it IS reflected in table A2 here:
https://taps-api.github.io/drafts/draft-trammell-taps-interface.html#rfc.appendix.A.2

I can't even find a suitable empty section in the implementation draft. Even the "maintenance" section: https://taps-api.github.io/drafts/draft-brunstrom-taps-impl.html#implementing-maintenance-events  seems to be about something else. If that's ok, I'll create a section and write text on how to implement the protocol properties in established state.

**Comment by theri** [comment]
For me, querying properties after establishment clearly belongs in a "Maintenance" section, perhaps a different subheading than the Maintenance events, so the top-level heading could just be "Implementing Maintenance". But those parts could also be merged later, I think.
The API draft probably needs a "Maintenance" section as well, see #29.

**Comment by britram** [comment]
note that this and #29 almost seem like duplicates of each other, so @mwelzl please make sure you're not hacking on the same stuff right now -- @theri notes in #29 that she's writing a section too...

**Comment by theri** [comment]
One is API (mine), one is Implementation (Michael's). I think we just have to make sure they match later
and I'm not planning to come up with anything radically new there.

**Comment by britram** [comment]
ahhhhh i missed the tags. sorry, thanks, carry on... :)

**Comment by mwelzl** [comment]
Querying is kinda trivial except for the size of a message before even connecting, but that's not in scope of this issue ("after establishment"). Setting, I just did (as a subsection of maintenance as suggested by @theri), so I'm done and I close this.
