### ISSUE TITLE
API section 5.1 no example of the “transport-agnostic” mode

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#56]
I think the current example misses the “transport-agnostic” mode, so I think we need a simple further example that includes more than “remoteSpecifier.withService("https”)”.

**Comment by britram** [comment]
actually, there seem to be examples without a service specifier; can you be more specific as to what you'd like to see here? (In any case, this doesn't seem blocking for -00)

**Comment by britram** [comment]
@gorryfair closing as inactive +  not-sure-what-the-problem-is, please reopen if you disagree.
