### ISSUE TITLE
API Section 7.1: Which items should we specify?

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#65]
I am really unsure I believe the transport should specify - see notes below:

/7.1.1.7. Immediate Acknowledgement /
- I suggest this is the wrong approach. I suggest the APP should ask for “low latency” and the stack should figure this out with respect to the protocols it is using. To me this seems like a direct protocol specific optimisation. How you do this in TCP v SCTP v foo-over-UDP all seem different, and unnecessary to expose for a generic interface.
/7.1.1.8. Send Bitrate/
- I vote to remove this for the reason above.

/7.1.1.9. Timeliness/
This specifies what delay characteristics the applications prefers for the given content. It provides hints for the transport system whether to optimize for low latency or other criteria and set the DSCP flags for packets used to transmit the content.
- - - -
/Stream/
- I vote to simplify this to Boolean.

**Comment by britram** [comment]
> /Stream/  I vote to simplify this to Boolean.

.. which "Stream"?

**Comment by gorryfair** [comment]
/Stream:
Delay and packet delay variation should be kept as low as possible
Interactive:
Delay should be kept as low as possible, but some variation is tolerable
Transfer:
Delay and packet delay variation should be reasonable, but are not critical
Background:
Delay and packet delay variation is no concern
The default is “Transfer”./
-My suggested boolean is /low-latency/.
- You could say this should be /low-latency/ 
- maybe also /low-jitter/, however, I'm not sure the endpoint typically finds low-jitter an easy quantity to race... the latter could be better handled by setting a PHB, for those networks that know how to use DSCPs.

**Comment by britram** [comment]
AH, ok.

Yeah this seems way easier to implement as a low-lat bool.

> I'm not sure the endpoint typically finds low-jitter an easy quantity to race

We probably shouldn't race metrics we can't even agree on a standard definition of. :)

**Comment by tfpauly** [comment]
I don't like the term Stream here at all; quite confusing.

As a reference, what we have in our implementation for this (and we use as already-public API) is an enum of Service Class fields, which are explicitly defined for use in on-device AQM queues for relative prioritization:
- Best Effort (default)
- Background (assumed to be bulk or opportunistic)
- Interactive Video
- Interactive Voice

These don't imply traffic pattern at all, like query/response, or streaming, etc, just the buckets we should use for queuing.

Also, +1 for the bool for low-latency (separately)

**Comment by britram** [comment]
I'll place a marker here to add a low-latency bool and move "timeliness" to an appendix...

**Comment by mwelzl** [comment]
A low-latency bool doesn't cut it as a replacement for "timeliness" - we also need to represent LBE. I think Gorry suggested the low latency bool as a replacement for the immediate ack thing (which makes sense to me).

**Comment by philsbln** [comment]
I agree with @tfpauly and @mwelzl arguments – I think we will need timeliness with changed levels.

We can save level-debate for post-london.

**Comment by gorryfair** [comment]
Actually, on timeliness:  I am quite OK with intended completion time. That is a connection value that an app can update in future also, if it has need. That's not the same as low-latency.

Gorry

**Comment by philsbln** [comment]
Ok - then we are talking about two different things here
- ``timeliness`` == ``capacity profile`` 
- ``duration`` == ``completion time``

Seems like we need to name and describe them better

**Comment by mwelzl** [comment]
I agree with this assessment

**Comment by britram** [comment]
Capacity Profile (and Instantaneous Capacity Profile for the send param) are what these are called in my editorial pass. I'm not extremely happy with them. I moved Duration to appendix A for now to move back out post-London. Shall we close this one out in favor of #90 for continued discussion?

**Comment by britram** [comment]
delayed close, go to #90 for more.
