### ISSUE TITLE
Section 5.2.2. Should mention properties for specific protocols

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#68]
Section 5.2.2. of the API should include the concept from the architecture of Specific Protocol Properties. I think expecting that all of these timeout/etc values should be the same no matter what protocol is selected is limiting, and a bit naive. I know as an application, for example, that I may need to do more keep alive activity to make NATs happy for UDP-based protocols than for TCP-based protocols (where are you, PLUS?!). 

Just a quick paragraph to indicate that the API can allow protocol-specific options to tune based on what is ultimately selected would be good.

**Comment by britram** [comment]
let's race candidate authors for this paragraph ;)

> where are you, PLUS?!

those who do not charter working groups for good ideas are doomed to forever reinvent them poorly.

**Comment by abrunstrom** [comment]
Is 5.2.2 supposed to be the Specific Protocol Properties section? This section also seems to be a mix of things right now. I think this needs to be fixed as part of a bigger rework of section 5.2.

**Comment by tfpauly** [comment]
Agreed. Check out my pull request—I switch the text to talking about the architecture concepts of Generic Protocol Properties and Specific Protocol Properties.

**Comment by abrunstrom** [comment]
That is better, but just a partial fix. I think we should get rid of the term Transport Preferences and the content of 5.2.1 and 5.2.2 needs to be reshuffled. Most of what is in 5.2.1 reads as protocol properties to me so I do not understand the current split.

**Comment by tfpauly** [comment]
That's fine with me. We could merge this PR in, and then as Brian does a pass, we can clean the rest up.
