### ISSUE TITLE
Write §6.4 (Connection Groups)

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#7]
We decided that connection groups (the construct by which we support multistreaming) are technically a pre-establishment-phase construct, but "get me a new connection in a connection group" seems like establishment in the eyes of the application. Discuss, and write text.

**Comment by britram** [comment]
suggest @mwelzl for this one, since it's the API equivalent of #17

**Comment by mwelzl** [comment]
Fine by me!  But I understand you folks didn't like my group IDs and instead wanted to have HTTP/2 / QUIC style. Also you were talking about "cloning" connections to get streams - this sounds easy enough as an approach, but is there a document describing this? Any pointer to a doc describing this style of opening streams? Of course I can invent something along these lines but then it's probably not quite what you have in mind - is there some documented basis for that thing that you want?

**Comment by tfpauly** [comment]
Section 4.1 in the Post Sockets draft has a drawing of how two connections are multiplexed on a stack. Section 2.1 also mentions that they're used for multistreaming.

In our API, we have a connection_create_with_connection() that takes an existing connection and opens a new stream on it that's multiplexed onto it. If you can't multiplex, this fails.

**Comment by britram** [comment]
One thing I didn't get in the discussion in Cambridge was the idea that this was a pre-establishment phase thing... yes, it's clear that you need a transport parameter to say "hey i might try to use multiple streams in a connection later, just saying..."

>In our API, we have a connection_create_with_connection() that takes an existing connection and opens a new stream on it that's multiplexed onto it. If you can't multiplex, this fails.

At one point IIRC, the PostSockets call for this was `Fork()`, which is probably just asking for confusion.

Open question: if you had a call like `InitiateClone()`, and you were running on top of a single streaming protocol stack, would it be acceptable not to fail, and to open a new flow to the same remote host/port?

**Comment by tfpauly** [comment]
Yes, you could certainly have the clone() call just work and create a parallel connection if needed.

I think the support for multiplexing either is an offshoot of the protocol that's selected, or something you request in the protocol selection parameters—"I prefer multiplexing"

**Comment by abrunstrom** [comment]
I still think it belongs to pre-establishment - you clone the selection parameters and then you initiate the connection - or the call combines pre-establishment and establishment - you clone the selection parameters and initiate the connection at the same time.

I prefer having the clone call just work and create a parallel connection if needed. That way the application does not have to be aware of what protocol is selected below.

If we want to support priorities, that parameter needs to be set separately in the clone call or through some other call.

**Comment by mwelzl** [comment]
Let's see if I understand. From bottom to top in your message, I agree about priorities and don't think this changes anything about what we're discussing here, and I don't think the app would have to be aware of the selected protocol either way.

So, about whether that happens in pre-establishment or establishment... IIUC what you mean with "prefer having the clone call just work" is that, if a connection hasn't yet been established but you already clone it, something "right" will happen. Makes sense to me, but only if we'd indeed always auto-connect upon cloning - else this is a little awkward, as you could end up with a connected clone but an unconnected parent.

**Comment by mwelzl** [comment]
Nonsense, both would be connected. Sorry, not yet awake!

**Comment by abrunstrom** [comment]
My comments concerned three independent points. The preference for the clone call just working referred to what should happen if the underlying protocol does not support multistreaming, as discussed by Brian and Tommy above.

**Comment by theri** [comment]
Just a quick note so we don't forget it:
The current §5.2 briefly mentions connection groups and should perhaps elaborate on them, e.g. regarding protocol selection properties that apply only to groups, and include a reference to §6.4 once it is written.
