### ISSUE TITLE
Only object-based or -oriented transport APIs?

### ISSUE THREAD

**Issue by karlgrin** [taps-api/drafts#72]
I have not been involved in the discussions than precedes the transport API, however, I still wonder if this api is only to be applicable to object-based and -oriented  programming languages such as Go, C++, C# etc. and not procedural such as C. When reading the architecture and interface I-Ds, it seems as a not altogether straightforward task to realize this in a procedural language.

**Comment by britram** [comment]
I don't see the issue. Certainly the language of the documents is aimed at more modern languages. This is on purpose. Part of the reason we need to move on from sockets is that they're rooted in a 1970s-era synchronous mindset.

It's the asynchronicity that makes the API harder to implement in straight C89, not the object orientedness. Object.Action(Arguments) is basically just syntactic sugar for Action(Object, Parameters); indeed, see how methods are defined in Python or Go for an illustration. (And even if you want polymorphic objects in C, you can implement them yourself with typed function pointers.)

Support for asynchronicity in C requires external libraries, though. Indeed, the reason the abstract API talks in fuzzy terms about "Events" is to avoid making any restriction about which patterns for implementing asynchronicity in such languages are allowed by the abstract API.

**Comment by tfpauly** [comment]
Yes, I think that the API does work in C, as long as you assume some model for asynchronous event delivery. The "objects" can just be typedef'ed structs, hopefully with some rudimentary reference count and locking. There are several options for the eventing library; for example, the one we use on Darwin-based platforms (libdispatch, also available for Linux) is aimed at C primarily.

**Comment by britram** [comment]
Reference counting? Locking? Man you really want to take all the fun out of C don't you? ;)

**Comment by karlgrin** [comment]
@tfpauly @britram: Let's close this issue. Seems that there are solutions for procedural languages such as C as well.
