### ISSUE TITLE
Arch: Termination

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#76]
Do I understand Termination? (section 3.2)
- To me this also includes how the remote endpoint discovers a graceful or premature end to the connection? - which implies the transition, is termination the correct word, or is this "terminated".

**Comment by tfpauly** [comment]
I'm a bit confused by this comment: the name of the Phase/Category of the architecture is Termination, by which the Application can gracefully or non-gracefully Terminate the Connections, after which point they are Terminated. It seems like the label for the category, like Establishment, is Termination.

**Comment by gorryfair** [comment]
OK - let's forget this comment and see how it all reads.
