### ISSUE TITLE
Arch Section 4: NiTs

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#77]
4.4.1:
/that Connection will use/
- insert /a/ before /connection/
---
I'm not hugely keen on /peer/ in this:
/Remote Endpoint: The Remote Endpoint represents the application’s name for a peer that can participate in a transport connection. For example, a DNS name for the peer./
- can we be simpler?
---
/This is critical to allow compatibility with Protocol Properties on peers./
- I don't know what that means. I agree with the remainder of this para.
---

**Comment by tfpauly** [comment]
Fixed, other than Peer, since I couldn't come up with a better phrasing yet.

**Comment by gorryfair** [comment]
This should not hold us back from publishing -00 draft. SO I am closing this.
