### ISSUE TITLE
Write §7 & §7.1 (Sending Data and Send Parameters)

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#8]
and note / design for the fact that an API that requires all send calls to always have all parameters won't get used for reasons of ugliness

**Comment by britram** [comment]
Uncovered in writing text for this: the transport parameters (#2) probably need to include a parameter to enable 0RTT establishment; i.e. that the first N Idempotent writes after Initiate() are intended to be 0RTT data.

**Comment by tfpauly** [comment]
Yes, the parameters do need to indicate that 0RTT should be waited for in general. Whether or not this needs to say how many idempotent writes are expected is a bit more debatable. Two other options:

- Allow idempotent send operations to be scheduled on the connection before start to be very explicit about which ones must be known about during the fast open start
- Just use whatever idempotent sends are around when connecting, which may be more for candidate transport stacks later in the racing schedule.

**Comment by britram** [comment]
(we should probably copy this over to #2...)

Another way to do this is to say that the API for 0RTT is different, and allow Send(Idempotent=true) to be taken as an implicit Initiate(). That might not play well with Rendezvous() if we define it though...

**Comment by tfpauly** [comment]
Yeah, I don't like having a different variant of Initiate as much. Properties about how protocols treat data should be set in pre-establishment, and not create new variants of establishment for different flavors of feature.

**Comment by mwelzl** [comment]
Idempotent data are messages, even in case of TFO, and an app programmer needs to know the max usable size for this message. This depends on the protocol options that the TAPS system will try... so this can only be available after initialize?!  Of course, we could always just allow a size that will *always* fit... I think that could be a reasonable trade-off for the reduced API complexity?

**Comment by mwelzl** [comment]
Also - sorry for complicating this, but there's the case of handing *non*-idempotent data over data before connecting. That's TCP with data on the SYN without TFO. Do we even care about this? While allowed in TCP, this isn't even properly defined in the RFC 793 API  :-)   I think we could ignore it...

**Comment by abrunstrom** [comment]
In NEAT we explicitly pass the data in during establishment with different initiate calls, using either a neat_open call or a neat_open_with_data call. Sending it after the initiate seems strange to me as you then either don't know if your data is available in time for the racing or you need a parameter in initiate to know that you need to wait for the idempotent data, then why not just send the data? Allowing idempotent send operations to be scheduled on the connection before initiate would be a clean approach I think.

**Comment by tfpauly** [comment]
Yes, what we use is that any send can be marked idempotent, but if you want it used for 0-RTT, send it before Initiate.

I prefer this to having something like neat_open_with_data, since that fundamentally modifies the establishment process.

**Comment by abrunstrom** [comment]
I would be happy with that, seems the most clean.

Do you use idempotent data sent in the middle of a connection for anything?

**Comment by tfpauly** [comment]
So, for our implementation, the main distinction is that making a Send idempotent disallows the app from setting any callback for when the content was sent. Since if we race idempotent data for multiple candidate flows, we may send it multiple times, you don't get to know if the data was sent or not.

When you mark a later send as idempotent, you also don't get a callback. 

The example we have for using the idempotent sends in this way is something like voice data that we want to start processing on a server, and we just want to send as much of it over as soon as possible. They're all marked idempotent so they are eligible for fast open if we need.

**Comment by britram** [comment]
Another use for this from earlier in Post Sockets' development  (before we added `Initiate()` back, IIRC): the API implementation could decide to switch a ~Carrier~Connection to another PSI, or could attempt to resume a PSI on connectivity loss, and it would be useful to know if such mid-flow resume or path migration could use 0RTT. See also the [cryptosep](https://datatracker.ietf.org/doc/draft-kuehlewind-taps-crypto-sep) draft.

That pattern isn't highlighted in this architecture / interface, but I don't think it should be precluded, either. In any case there is a benefit in getting the application to tell the transport on a per-`Send()` basis about idempotence, since that information may be useful to the transport, and not just when the application decides to initiate. (since initiation from the means "you can't change your mind about the parameters anymore", not "this connection becomes irrevocably bound to one and only one PSI during the lifetime of the connection", though that is certainly an acceptable behavior for lazy implementations).

**Comment by britram** [comment]
also, @tfpauly says:

> When you mark a later send as idempotent, you also don't get a callback.

This seems weird to me. Can you say more?

**Comment by britram** [comment]
since the first pass of this section is done, closing the issue. file new issues for discussion on things you don't like in the text...
