### ISSUE TITLE
ARCh: Content-related actions...

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#80]
/This should deliver a useful error to the application./
- I understand what was intended, but errors are not usually useful in a sense. Should this be:
/This should deliver an error that the application is able to utilise./
---
/Content Received: A Content Received event delivers received content to the application, based on a Receive action. This may include an error if the action failed./
- I don't yet understand the error part to this.

**Comment by tfpauly** [comment]
Fixed, and clarified the receive error.
