### ISSUE TITLE
Arch: an indication that Content has been acknowledged by a peer

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#81]
The text describes and event: /an indication that Content has been acknowledged by a peer./
- I don't agree/understand, in the way I see this, the sender should receive the signal as soon as the content leaves the interface, it shouldn't delay to wait and see if the data went through the network - I actually think this idea of per-layer ACKs is dangerous. If an app wishes to know the data has made it, then it should add PDUs to the remote endpoint to ask that, not trust the transport with that responsibility. Many TCP-based apps have fallen foul of assumptions about what happens with data received by the remote stack. I'd like to see that removed as a feature.

**Comment by tfpauly** [comment]
Sounds good, agreed.

**Comment by tfpauly** [comment]
Removed!
