### ISSUE TITLE
GF Author block details

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#83]
My full author block is below, can someone edit this in next pass please for me in Arch and  API:

   Godred Fairhurst
   University of Aberdeen
   Department of Engineering
   Fraser Noble Building
   Aberdeen, AB24 3UE
   Scotland

   Email: gorry@erg.abdn.ac.uk
   URI:   http://www.erg.abdn.ac.uk/

**Comment by tfpauly** [comment]
Updated!
