### ISSUE TITLE
ARCH: RFC 2119 language used.

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#84]
Section 4.1.1 contains some text that looks like RFC Requirements, but we don't say this as a requirements docment. And we don't include the boilerplate explaining RFC2119.

My Recommendation: I'd be happy enough to see this section just use lower case keywords. There's a few of these across the document describing the way it should work which currently look non-normative to me. We could always revisit this in a later revision if there is agreement that we should include RFC2119 keywords, but then we need to carefully review each usage:-).

However..., the Security Considerations still uses normative language. My hope is these could also be lower case?

**Comment by tfpauly** [comment]
Good call. We may want to add some back later, but we don't need it now!
