### ISSUE TITLE
Unable to compile draft-brunstrom-taps-impl

### ISSUE THREAD

**Issue by karlgrin** [taps-api/drafts#86]
@mwelzl could you please make sure that your latest revision of the implementation draft compiles.

**Comment by tfpauly** [comment]
Fixed compilation for now, but I had to remove Michael as an author. I tried many variations, but the xml output was always invalid?

**Comment by mwelzl** [comment]
Very sorry! I fixed this now (I insist on co-authorship  :-D  ) - I think it came from copy+pasting, the block said that I'm an editor... maybe that didn't work out.

**Comment by tfpauly** [comment]
@mwelzl Great! Yes, you indeed should be an author. =) I felt bad for removing you, but it wasn't building. I event removed the editor line, but that didn't make a difference. Glad it's cleared up now.

**Comment by mwelzl** [comment]
Never mind  :)   I hope it doesn't only compile on my system now...  but here things seem fine

**Comment by tfpauly** [comment]
Checked it on my system, and it compiles now.

**Comment by mwelzl** [comment]
I assume we both have a Mac  :-)  :-)
