### ISSUE TITLE
Rename Association cache

### ISSUE THREAD

**Issue by abrunstrom** [taps-api/drafts#87]
In Figure 1 and 4.2 we use the term Association Cache. I think this name is too narrow and confusing and it is not aligned with what we have in the implementation draft. I suggest renaming this to Cached State or Protocol and Performance Caches. The text in 4.2 can borrow from the implementation draft and be updated to:
"Beyond a single Connection's lifetime, it is useful for an implementation to keep state and history. This cached state can help improve future Connection establishment due to re-using results and credentials, and favoring paths and protocols that performed well in the past. It can include DNS results, TLS session state, previous success and quality of transport protocols over certain paths."

**Comment by tfpauly** [comment]
Updated in architecture to Cached State to be consistent
