### ISSUE TITLE
Consistency of Design Principles

### ISSUE THREAD

**Issue by abrunstrom** [taps-api/drafts#88]
The architecture draft has a number of design principles listed (the ones discussed in Cambridge). The API draft has a another set of design principles listed. When reading both drafts as I just did, this is quite confusing. Do we need design principles in the API draft or they should all move to the architecture draft? Some of the design principles in the API draft are perhaps more detailed which could be an argument to keep them in the API draft, but then I think we should at least make sure to include all design principles from the architecture draft that applies to the API also in the API draft. Right now we have only one of them which is strange.

**Comment by britram** [comment]
IMO the principles in the Architecture document are primary. The list in API as it stands is largely inherited from Post Sockets. Though the list of principles in the API is more detailed (and I think we need more detailed principles for the API), it should refer back more concretely to the arch principles. I'll do this in my early-week edit pass.

**Comment by tfpauly** [comment]
Agreed. So, can we leave the architecture list as-is, and maybe re-name the section in the API?

**Comment by britram** [comment]
Open to suggestions for naming (I would have just called it "Interface Design Principles")... API section will have to expand a little from its current bullet-list to base itself on arch principles.
